function _exito() {
  const codigos = JSON.parse(sessionStorage.getItem("codigos") || "{}");
  sessionStorage.setItem(
    "codigos",
    JSON.stringify({
      ...codigos,
      fasepreguntas: { codigo: "1GR46", link: "fase-preguntas" },
    })
  );
  $("#myModal").show();
}

$("#quiz").quiz({
  finishCallback: _exito,
  resultsScreen: "#results-screen",
  counter: true,
  counterFormat: "Pregunta %current de %total",
  questions: [
    {
      q: "Una cosa molt dolça que et van regalar quan vas fer 22 anys.",
      options: ["Donuts", "Xuxes"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Lloc del restaurant on vas celebrar els 18 anys.",
      options: ["A casa", "Xivarri", "Mas Fleca"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom de la professora de segon de primària.",
      options: ["Margarida", "Rosa", "Rosalía"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom de la classe de primària del Ribatallada.",
      options: ["Xiprers", "Avets", "Roures"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom del millor amic que tenies a L’Escola.",
      options: ["Borja", "Jordi"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom de la gossa amb qui anaves a la Mola.",
      options: ["Safo", "Lluna"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Població marítima on vas aprendre a anar amb bicicleta.",
      options: ["Altafulla", "Comarruga", "L'Ametlla de Mar"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom de l’escola de dansa on feies ballet.",
      options: ["Driss Dansa", "Ritme", "Boots"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Destinació del viatge de final d’ESO.",
      options: ["Mallorca", "Menorca", "Eivissa"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Ciutat de UK on se situen unes termes romanes.",
      options: ["Bristol", "Bath"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Instrument musical important a la teva vida.",
      options: ["Castanyoles", "Acordió", "Clarinet"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Idioma que mai no has volgut aprendre.",
      options: ["Esperanto", "Anglès", "Mandarí"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom de Ciutadella inca situada a gran alçada.",
      options: ["Machu Picchu", "Tiahuanaco", "Piràmide del Sol"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Illa de la Mediterrània on parlen català.",
      options: ["Corsega", "Lampedusa", "Cerdenya"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Part del cos que feia mal quan tenies problemes de creixement.",
      options: ["Genoll", "Espatlla"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Mal de orelles.",
      options: ["Acné", "Otitis"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Soroll fort i confús. També nom d’esplai.",
      options: ["Xafarranxo", "Aldarull", "Xivarri"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Saga literaria de mags",
      options: ["Harry Potter", "Els 4 fantàstics"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Nom d’instrument musical de vent i de cotxe.",
      options: ["Audi", "Saxo"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "País andí sense litoral",
      options: ["Ecuador", "Perú", "Bolívia"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Ciutat que avui també celebra el seu aniversari.",
      options: ["El Alto", "El Bajo", "El Mitja"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "El nom d’aquesta ciutat significa “En la loma o cima de los guajes”.",
      options: ["Michoacán", "Oaxaca"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "De qui és la frase: “Pies para qué los quiero si tengo alas para volar”.",
      options: ["Frida Khalo", "Sòcrates"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Estació de Barcelona dels FFCC.",
      options: ["Estació central", "Recoletos", "Muntaner"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Institut de Terrassa que vas visitar durant uns cursos.",
      options: ["Santa Claudia", "Santa Llúcia", "Santa Eulàlia"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Te’l va portar la pandèmia.",
      options: ["L'Albert", "Els escape rooms", "La mascareta"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Pous subterranis característics de Mèxic. Són de gran profunditat i fins i tot, en alguns d’ells t’hi pots banyar.",
      options: ["Llacs", "Cenote"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Ciutat de la Costa Brava famosa per les seves gambes.",
      options: ["Vinarós", "Palamós", "Rocafulla"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Musa de la Història.",
      options: ["Nike", "Atenea", "Clio"],
      correctIndex: 2,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Les mosques, els mosquits, orugues, llagostes, puces... ho són",
      options: ["Bitxo", "Fastigosos"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
  ],
});
