function _exito() {
  const codigos = JSON.parse(sessionStorage.getItem("codigos") || "{}");
  sessionStorage.setItem(
    "codigos",
    JSON.stringify({
      ...codigos,
      faseHistoria: { codigo: "3QJ05", link: "fase-historia" },
    })
  );
  $("#myModal").show();
}

$("#quiz").quiz({
  finishCallback: _exito,
  resultsScreen: "#results-screen",
  counter: true,
  counterFormat: "Pregunta %current de %total",
  questions: [
    {
      q: "Quin dia de la setmana va ser el 1r de gener?",
      options: ["Dissabte", "Dimecres", "Divendres"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Qui governava els EUA?",
      options: ["George Washington", "George H.W. Bush", "Ronald Reagan"],
      correctIndex: 1,
      correctResponse: "",
      incorrectResponse: "",
    },
    {
      q: "Hi va haver supervivents a l’accident aeri de l’ Airbus A320 que feia la ruta Lió-Estrasburg?",
      options: ["Si", "No"],
      correctIndex: 0,
      correctResponse: "",
      incorrectResponse: "",
    },
    // {
    //   q: "Va intentar donar un cop d’estat a Veneçuela l’Hugo Chávez?",
    //   options: ["No", "Si"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin dia es va establir la UE?",
    //   options: ["6 de març", "9 d'agost", "7 de febrer"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin film va guanya el premi a la millor pel·lícula als Goya?",
    //   options: ["El dia de la bèstia", "La passió Turca", "Amantes"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Nom de l’esquiadora espanyola que va guanyar el bronze als JJOO de Albertville.",
    //   options: ["Blanca Fernández Ochoa", "María José Rienda"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quan s’estrena la sèrie Sailor Moon?",
    //   options: ["12 de gener", "20 de septembre", "7 de març"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin país va esdevenir independent el 7 d’abril de 1992?",
    //   options: ["El Congo", "Bosnia-Herzegovina", "Filipinas"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quina línia de l’AVE es va inaugurar el 14 d’abril?",
    //   options: ["Barcelona-Valencia", "Madrid-Sevilla", "Madrid-Valencia"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quan s’inaugura l’EXPO de Sevilla?",
    //   options: ["14 d'agost", "2 de juliol", "20 d'abril"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "El 30 d’abril explota a Rosario (Argentina) una granada davant de la casa natal d’un revolucionari i guerriller molt famós.",
    //   options: ["Ernesto Che Guevara", "Simón Bolivar", "Fidel Castro"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Qui va guanyar el Festival d’Eurovisión?",
    //   options: ["Salomé", "Massiel", "Linda Martin"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin equip va guanyar la Supercopa d’Europa al Wembley Stadium?",
    //   options: ["Real Madrid", "Barcelona FC", "CE Sabadell"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin àlbum llença al mercat Elton John?",
    //   options: ["The Two", "The One", "The Three"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin narco colombià es va escapar de presó?",
    //   options: ["El Dioni", "Sito Miñanco", "Pablo Escobar"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Qui és el president del govern espanyol?",
    //   options: ["Felipe González", "Julio Anguita", "Jose M Aznar"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin dia s’inauguren els JJOO de Barcelona?",
    //   options: ["25 de juliol", "3 de julios", "14 de juny"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Qui va guanyar el tour de França?",
    //   options: ["Perico Delgado", "Luis Ocaña", "Miguel Induráin"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Nom de l’huracà que devasta l’illa de Hawai el mes de setembre.",
    //   options: ["Iniki", "Kaleni", "Uholo"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Nom de la guanyadora del Premi Nobel de la Pau",
    //   options: ["Teresa de Calcuta", "Rigoberta Menchú"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Joan Pau II reconeix que va ser injusta la condemna que l’església catòlica va fer amb un científic, quin?",
    //   options: ["Miguel Servet", "Galileo Galilei", "Nicolau Copernic"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quin festival va guanyar el cantant Francisco?",
    //   options: ["Eurovisió", "OTI", "Operació Triomf"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Qui va guanyar el premi Nadal?",
    //   options: ["Alberto Chicote", "Francisco Umbral", "Alejandro Gándara"],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Qui va guanyar el premi Cervantes?",
    //   options: ["Dulce Maria Loynaz", "Dulce Chacón", "Dulce Salado"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Qui va guanyar el premi Princep d’Astúries de de les Arts?",
    //   options: ["Alfredo Kraus", "Roberto Matta Echaurren", "Teresa Berganza"],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quina actriu va guanyar l’Òscar el 1992?",
    //   options: ["Jodie Foster", "Siguiner Wiver", "Sharon Stone"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quina actriu va guanyar el Goya el 1992?",
    //   options: ["Penélope Cruz", "Marisa Paredes", "Beatriz Carvajal"],
    //   correctIndex: 0,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quina cançó es va fer molt popular aquell estiu?",
    //   options: [
    //     "Sobreviviré de Monica Naranjo",
    //     "Déjame de Los Secretos",
    //     "Amigos para siempre de Los Manolos",
    //   ],
    //   correctIndex: 2,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
    // {
    //   q: "Quina novel·la va vendre prop de 2,5 milions d'exemplars?",
    //   options: [
    //     "La casa de los espíritus de Isabel Allende",
    //     "Corazón tan blanco de Javier Marías",
    //     "El Alquimista de Paolo Coello",
    //   ],
    //   correctIndex: 1,
    //   correctResponse: "",
    //   incorrectResponse: "",
    // },
  ],
});
